### ISSUE TITLE
provide API reference

### ISSUE THREAD

**Issue by fricklerhandwerk** [Tagirijus/ledger-parse#1]
Please flesh out what the interface of your library looks like, i.e. what it expects and what it provides. It's hard to distinquish from the code what it is trying to do.

**Comment by Tagirijus** [comment]
It's not that detailed, but it might work for the beginning. Maybe I am going to change a few things in the future anyway (like using decimal.Decimal() instead of my own ledgerparse.Money() object ...). Hope the new readme helps understanding the module a bit better now.
